[default]
GOOGLE_API_KEY = "AIzaSyDUkq0nrIXwPfVkS3tgagS7zV6EtCMPSss"
PINECONE_API_KEY = "pcsk_3aziQH_FhYmdBpXgFTL6borDTmnUcMFSnsXd55CXq5YdYmge17qF14iQP7ZScvAXxnT261"
PINECONE_ENVIRONMENT = "us-east-1"
